name: Release

on:
  push:
    tags:
      - '*'

env:
  PIP_DISABLE_PIP_VERSION_CHECK: on
  PIP_DEFAULT_TIMEOUT: 10
  PIP_PROGRESS_BAR: off

jobs:
  quality-control:
    uses: ./.github/workflows/test.yml

  pypi-upload:
    needs: [ quality-control ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          pip install pip -U
          pip install build wheel twine
      - name: Upload pypi package
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "__version__ = \"$VERSION\"" > src/gpuhunt/version.py
          python -m build
          python -m twine upload --repository pypi --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} dist/*
