name: Release

on:
  push:
    tags:
      - '*'

jobs:
  quality-control:
    uses: ./.github/workflows/test.yml

  pypi-upload:
    needs: [ quality-control ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13
      - name: Build package
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "__version__ = \"$VERSION\"" > src/gpuhunt/version.py
          uv build
      - name: Upload package to PyPI
        run: uv publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
